# Generated by Django 5.1.3 on 2025-02-21 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catFishFarm', '0002_staffmember_alter_expensebreakdown_payee_staff_and_more'),
        ('company', '0050_alter_activityowner_reoccurring_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='name',
            field=models.CharField(default='kinmgsley', help_text="Staff member's name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['company', 'farm'], name='catFishFarm_company_b291f4_idx'),
        ),
    ]
