# Generated by Django 5.1.3 on 2025-02-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catFishFarm', '0003_staffmember_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='name',
        ),
    ]
