# Generated by Django 5.1.3 on 2025-02-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catFishFarm', '0004_remove_staffmember_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PondCondition',
            new_name='PondWaterCondition',
        ),
        migrations.AlterField(
            model_name='pond',
            name='depth',
            field=models.DecimalField(decimal_places=2, help_text='Depth in feet', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pond',
            name='size',
            field=models.DecimalField(decimal_places=2, help_text='Size in cubic feet', max_digits=10),
        ),
        migrations.CreateModel(
            name='PondMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('maintenance_type', models.CharField(choices=[('repair', 'Repair'), ('treatment', 'Treatment'), ('cleaning', 'Cleaning'), ('covering', 'Covering'), ('other', 'Other')], max_length=255)),
                ('description', models.TextField(help_text='Details of the maintenance activity')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Who performed the maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='catFishFarm.pond')),
            ],
        ),
    ]
