# Generated by Django 5.1.3 on 2025-02-23 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catFishFarm', '0005_rename_pondcondition_pondwatercondition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pondmaintenancelog',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to this maintenance task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='catFishFarm.staffmember'),
        ),
        migrations.AddField(
            model_name='pondmaintenancelog',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Who completed the maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pondmaintenancelog',
            name='completed_date',
            field=models.DateField(blank=True, help_text='Date when the maintenance was completed', null=True),
        ),
        migrations.AddField(
            model_name='pondmaintenancelog',
            name='cost_of_maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the maintenance activity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pondmaintenancelog',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for the maintenance activity', null=True),
        ),
        migrations.AddField(
            model_name='pondmaintenancelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pondmaintenancelog',
            index=models.Index(fields=['pond', 'date'], name='catFishFarm_pond_id_5c31b0_idx'),
        ),
    ]
