# Generated by Django 5.1.3 on 2024-11-29 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_staff_work_email_alter_staff_work_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the farm.', max_length=255)),
                ('description', models.TextField(help_text='General description of the farm.')),
                ('established_date', models.DateField(help_text='Date the farm was established.')),
                ('location', models.CharField(help_text='Location of the farm.', max_length=255)),
                ('contact_number', models.CharField(help_text='Contact number for the farm.', max_length=20)),
                ('email', models.EmailField(help_text='Email address for inquiries.', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Website URL of the farm.', null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='farm/profile_images/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='farm/background_images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('closed', 'Closed')], default='inactive', help_text='Current operational status of the farm.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='company.company')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
