# Generated by Django 5.1.3 on 2024-12-03 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0004_alter_staffmember_unique_together'),
        ('company', '0005_alter_authority_unique_together_authority_app_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Net (Love Cage).', max_length=255)),
                ('length', models.FloatField(help_text='Length of the Net in meters.')),
                ('width', models.FloatField(help_text='Width of the Net in meters.')),
                ('height', models.FloatField(help_text='Height of the Net in meters.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('broken', 'Broken')], default='active', help_text='Status of the Net.', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the Net was created.')),
                ('company', models.ForeignKey(help_text='The company owning the Net.', on_delete=django.db.models.deletion.CASCADE, related_name='nets', to='company.company')),
                ('farm', models.ForeignKey(help_text='The farm to which the Net is assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='nets', to='bsf.farm')),
            ],
            options={
                'verbose_name': 'Net',
                'verbose_name_plural': 'Nets',
                'unique_together': {('name', 'farm', 'company')},
            },
        ),
    ]
