# Generated by Django 5.1.3 on 2024-12-04 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0005_net'),
        ('company', '0005_alter_authority_unique_together_authority_app_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=10)),
                ('laying_start_date', models.DateField(blank=True, null=True)),
                ('laying_end_date', models.DateField(blank=True, null=True)),
                ('laying_harvest_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('laying_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('laying_expectation_reached', models.IntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Exceeds Fully Successful'), (3, 'Fully Successful'), (2, 'Minimally Satisfactory'), (1, 'Unsatisfactory')], null=True)),
                ('incubation_start_date', models.DateField(blank=True, null=True)),
                ('incubation_end_date', models.DateField(blank=True, null=True)),
                ('incubation_start_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('incubation_harvest_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('incubation_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('incubation_expectation_reached', models.IntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Exceeds Fully Successful'), (3, 'Fully Successful'), (2, 'Minimally Satisfactory'), (1, 'Unsatisfactory')], null=True)),
                ('nursery_start_date', models.DateField(blank=True, null=True)),
                ('nursery_end_date', models.DateField(blank=True, null=True)),
                ('nursery_start_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('nursery_harvest_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('nursery_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('nursery_expectation_reached', models.IntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Exceeds Fully Successful'), (3, 'Fully Successful'), (2, 'Minimally Satisfactory'), (1, 'Unsatisfactory')], null=True)),
                ('growout_start_date', models.DateField(blank=True, null=True)),
                ('growout_end_date', models.DateField(blank=True, null=True)),
                ('growout_start_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('growout_harvest_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('growout_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('growout_expectation_reached', models.IntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Exceeds Fully Successful'), (3, 'Fully Successful'), (2, 'Minimally Satisfactory'), (1, 'Unsatisfactory')], null=True)),
                ('puppa_start_date', models.DateField(blank=True, null=True)),
                ('puppa_end_date', models.DateField(blank=True, null=True)),
                ('puppa_start_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('puppa_harvest_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('puppa_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('puppa_expectation_reached', models.IntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Exceeds Fully Successful'), (3, 'Fully Successful'), (2, 'Minimally Satisfactory'), (1, 'Unsatisfactory')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='company.company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='bsf.farm')),
            ],
            options={
                'unique_together': {('batch_name', 'farm')},
            },
        ),
    ]
