# Generated by Django 5.1.3 on 2024-12-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0007_batch_cretated_by'),
        ('company', '0006_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laying_duration', models.PositiveIntegerField(default=0, help_text='Duration for laying in days')),
                ('nursery_duration', models.PositiveIntegerField(default=0, help_text='Duration for nursery in days')),
                ('incubation_duration', models.PositiveIntegerField(default=0, help_text='Duration for incubation in days')),
                ('growout_duration', models.PositiveIntegerField(default=0, help_text='Duration for grow-out in days')),
                ('puppa_in_net_replenishment_duration', models.PositiveIntegerField(default=0, help_text='Duration for puppa replenishment in days')),
                ('feed1_fermentation_period', models.PositiveIntegerField(default=0, help_text='Duration for feed1 fermentation in days')),
                ('feed2_fermentation_period', models.PositiveIntegerField(default=0, help_text='Duration for feed2 fermentation in days')),
                ('attractant_duration', models.PositiveIntegerField(default=0, help_text='Duration for attractant in days')),
                ('general_inspection_duration', models.PositiveIntegerField(default=0, help_text='Duration for general inspection in days')),
                ('net_cleanup_duration', models.PositiveIntegerField(default=0, help_text='Duration for net cleanup in days')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_settings', to='company.company')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duration_settings', to='company.branch')),
            ],
        ),
    ]
