# Generated by Django 5.1.3 on 2024-12-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0008_durationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durationsettings',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duration_settings', to='bsf.farm'),
        ),
    ]
