# Generated by Django 5.1.3 on 2024-12-05 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0009_alter_durationsettings_farm'),
        ('company', '0006_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='durationsettings',
            unique_together={('company', 'farm')},
        ),
        migrations.CreateModel(
            name='NetUseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lay_start', models.DateTimeField()),
                ('lay_end', models.DateTimeField(blank=True, null=True)),
                ('harvest_weight', models.FloatField(default=0, help_text='Harvest weight in grams')),
                ('stats', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_net_use_stats', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_use_stats', to='bsf.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_use_stats', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_net_use_stats', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_use_stats', to='bsf.farm')),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_use_stats', to='bsf.net')),
            ],
        ),
    ]
