# Generated by Django 5.1.3 on 2024-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0010_alter_durationsettings_unique_together_netusestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netusestats',
            name='harvest_weight',
            field=models.FloatField(blank=True, help_text='Harvest weight in grams', null=True),
        ),
    ]
