# Generated by Django 5.1.3 on 2024-12-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0011_alter_netusestats_harvest_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='netusestats',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_net_use_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
