# Generated by Django 5.1.3 on 2024-12-10 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0012_alter_netusestats_created_by'),
        ('company', '0006_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_name', models.CharField(max_length=255, unique=True, verbose_name='Pond Name')),
                ('pond_type', models.CharField(choices=[('Concrete', 'Concrete'), ('Rubber-Tire', 'Rubber-Tire')], max_length=20, verbose_name='Pond Type')),
                ('pond_use', models.CharField(choices=[('Incubator', 'Incubator'), ('Nursery', 'Nursery'), ('Grow Out', 'Grow Out'), ('Multiple', 'Multiple')], max_length=20, verbose_name='Pond Use')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Width (meters)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length (meters)')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depth (meters)')),
                ('shape', models.CharField(choices=[('Circular', 'Circular'), ('Rectangular', 'Rectangular'), ('Square', 'Square')], max_length=20, verbose_name='Pond Shape')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Broken', 'Broken')], default='Active', max_length=20, verbose_name='Pond Status')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='company.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='bsf.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Pond',
                'verbose_name_plural': 'Ponds',
                'constraints': [models.UniqueConstraint(fields=('pond_name', 'farm', 'company'), name='unique_pond_name_per_farm_and_company')],
            },
        ),
    ]
