# Generated by Django 5.1.3 on 2024-12-10 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0013_pond'),
        ('company', '0006_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PondUseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_date', models.DateField(verbose_name='Set Date')),
                ('harvest_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harvest Weight (kg)')),
                ('harvest_stage', models.CharField(choices=[('First Insta', 'First Insta'), ('Second Insta', 'Second Insta'), ('Fifth Insta', 'Fifth Insta'), ('PrePupa', 'PrePupa'), ('Pupa', 'Pupa')], max_length=20, verbose_name='Harvest Stage')),
                ('pond_name', models.CharField(editable=False, max_length=255, verbose_name='Pond Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20, verbose_name='Status')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('approver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pond_use_stats', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_use_stats', to='bsf.batch', verbose_name='Batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_use_stats', to='company.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pond_use_stats', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_use_stats', to='bsf.farm', verbose_name='Farm')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_use_stats', to='bsf.pond', verbose_name='Pond')),
            ],
            options={
                'verbose_name': 'Pond Use Stats',
                'verbose_name_plural': 'Pond Use Stats',
            },
        ),
    ]
