# Generated by Django 5.1.3 on 2024-12-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0014_pondusestats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pondusestats',
            old_name='set_date',
            new_name='harvest_date',
        ),
        migrations.AddField(
            model_name='pondusestats',
            name='start_date',
            field=models.DateField(default='2024-12-10', verbose_name='Set Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pondusestats',
            name='start_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Harvest Weight (grams)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pondusestats',
            name='harvest_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Harvest Weight (kg)'),
        ),
    ]
