# Generated by Django 5.1.3 on 2024-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0015_rename_set_date_pondusestats_harvest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondusestats',
            name='harvest_date',
            field=models.DateField(verbose_name='Harvest Date'),
        ),
        migrations.AlterField(
            model_name='pondusestats',
            name='start_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Start Weight (g)'),
        ),
    ]
