# Generated by Django 5.1.3 on 2024-12-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0016_alter_pondusestats_harvest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondusestats',
            name='harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Harvest Date'),
        ),
    ]
