# Generated by Django 5.1.3 on 2024-12-29 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0019_staffmember_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netusestats',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='netusestats',
            name='lay_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='netusestats',
            name='lay_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
