# Generated by Django 5.1.3 on 2024-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0021_alter_netusestats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netusestats',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
