# Generated by Django 5.1.3 on 2024-12-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0022_alter_netusestats_updated_at'),
        ('company', '0026_branch_contact_number_branch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='company.branch'),
            preserve_default=False,
        ),
    ]
