# Generated by Django 5.1.3 on 2025-01-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0024_netusestats_expect_harvest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netusestats',
            name='expect_harvest',
        ),
    ]
