# Generated by Django 5.1.3 on 2025-01-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0026_net_expect_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='netusestats',
            name='ratting',
            field=models.CharField(choices=[('outstanding', 'Outstanding'), ('exceeds_expectation', 'Exceeds Expectation'), ('satisfactory', 'Satisfactory'), ('unsatisfactory', 'Unsatisfactory'), ('poor', 'Poor')], default='unsatisfactory', max_length=40),
        ),
    ]
