# Generated by Django 5.1.3 on 2025-01-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0027_netusestats_ratting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netusestats',
            old_name='ratting',
            new_name='laying_ratting',
        ),
    ]
