# Generated by Django 5.1.3 on 2025-02-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsf', '0031_pondusestats_laying_ratting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='branch',
        ),
    ]
