# Generated by Django 5.1.3 on 2024-12-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authority',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authority',
            name='app_name',
            field=models.CharField(default='none', help_text='Name of the app the model belongs to.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authority',
            name='model_name',
            field=models.CharField(help_text='Name of the target model.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='authority',
            unique_together={('model_name', 'app_name', 'company')},
        ),
    ]
