# Generated by Django 5.1.3 on 2024-12-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_activityowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
