# Generated by Django 5.1.3 on 2024-12-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityowner',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_owners', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='activityowner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_owners', to='company.company'),
        ),
    ]
