# Generated by Django 5.1.3 on 2024-12-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_remove_task_assitant_task_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appName',
            field=models.CharField(default='bsf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityowner',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='company.branch'),
        ),
    ]
