# Generated by Django 5.1.3 on 2024-12-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_activityowner_appname_activityowner_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm', to='company.branch'),
        ),
    ]
