# Generated by Django 5.1.3 on 2024-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_task_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='farm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
