# Generated by Django 5.1.3 on 2024-12-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_task_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
    ]
