# Generated by Django 5.1.3 on 2024-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for the Sector.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the branch.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for inquiries.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='established_date',
            field=models.DateField(blank=True, help_text='Date the Sector was established.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the Sector.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL of the Sector.', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='appName',
            field=models.CharField(default='company', max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='modelName',
            field=models.CharField(default='branch', max_length=255),
        ),
    ]
