# Generated by Django 5.1.3 on 2024-12-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_branch_contact_number_branch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completeDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
