# Generated by Django 5.1.3 on 2025-01-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_task_completedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='reward_factor',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Reward factor as a percentage of the salary', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Monthly salary of the staff', max_digits=15, null=True),
        ),
    ]
