# Generated by Django 5.1.3 on 2025-01-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_staff_reward_factor_staff_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='reward',
            field=models.BooleanField(default=False, help_text='Determines if the user is eligible for reward points upon task completion.'),
        ),
    ]
