# Generated by Django 5.1.3 on 2025-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_staff_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('fired', 'Fired'), ('retired', 'Retired'), ('resigned', 'Resigned'), ('pending', 'Pending')], default='active', max_length=10),
        ),
    ]
