# Generated by Django 5.1.3 on 2025-01-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_branch_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='county',
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the branch is located.', max_length=255, null=True),
        ),
    ]
