# Generated by Django 5.1.3 on 2025-01-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_remove_branch_county_branch_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefaultSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('appName', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('min_count', models.PositiveIntegerField(help_text='Minimum count for the activity.')),
            ],
            options={
                'verbose_name': 'Activity Default Setting',
                'verbose_name_plural': 'Activity Default Settings',
            },
        ),
        migrations.AddField(
            model_name='activityowner',
            name='min_estimated_count',
            field=models.PositiveIntegerField(default=0, help_text='Minimum estimated amount (times, count) the activity needs to be performed every month.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='reward_factor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reward factor as a percentage of the salary', max_digits=5, null=True),
        ),
    ]
