# Generated by Django 5.1.3 on 2025-01-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_activitydefaultsetting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityowner',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_owners', to='company.activitydefaultsetting'),
        ),
        migrations.AlterField(
            model_name='activityowner',
            name='activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activityowner',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='company.branch'),
        ),
    ]
