# Generated by Django 5.1.3 on 2025-01-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_activityowner_default_alter_activityowner_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityowner',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityowner',
            name='min_estimated_count',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum estimated amount (times, count) the activity needs to be performed every month.', null=True),
        ),
    ]
