# Generated by Django 5.1.3 on 2025-01-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_alter_activityowner_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityowner',
            name='importance_scale',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, help_text="Importance scale from 1 to 5 indicating how crucial the activity execution is to the success of the company's branch."),
        ),
    ]
