# Generated by Django 5.1.3 on 2025-01-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_alter_activityowner_importance_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityowner',
            name='dataQuantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of times modelName has to be filled out per task completion.'),
        ),
        migrations.AddField(
            model_name='activityowner',
            name='mustFill',
            field=models.CharField(blank=True, help_text='This is a test field that indicates what dataset must be filled out in the model (modelName) for the activity to be considered completed.', max_length=255, null=True),
        ),
    ]
