# Generated by Django 5.1.3 on 2025-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_activityowner_dataquantity_activityowner_mustfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appealReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='dataQuantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of times modelName has to be filled out per task completion.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('appeal', 'appeal'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
