# Generated by Django 5.1.3 on 2025-01-02 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_task_appealreason_task_dataquantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardsPointsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, help_text='Points received for the task', max_digits=10, null=True)),
                ('credit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date the points were received', null=True)),
                ('point_conversion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Conversion rate of points to currency', max_digits=10, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Points used by the user', max_digits=10, null=True)),
                ('debit_date', models.DateTimeField(blank=True, help_text='Date the points were used', null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments regarding the points transaction', null=True)),
                ('points_available', models.DecimalField(decimal_places=2, default=0, help_text='Points available for use', max_digits=10)),
                ('points_pending', models.DecimalField(decimal_places=2, default=0, help_text='Points pending approval', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_points', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_points', to='company.company')),
                ('debit_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_points', to=settings.AUTH_USER_MODEL)),
                ('debit_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_requests', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_points', to='company.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rewards Points Tracker',
                'verbose_name_plural': 'Rewards Points Trackers',
                'ordering': ['-credit_date'],
            },
        ),
    ]
