# Generated by Django 5.1.3 on 2025-01-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_rewardspointstracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardspointstracker',
            name='blocked',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points blocked due to non task completion at all or in a timely manner', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rewardspointstracker',
            name='transaction_type',
            field=models.CharField(choices=[('merit', 'Merit'), ('assisted', 'Assisted'), ('staffMember', 'Staff Member')], default='merit', help_text='Type of transaction (merit, assisted, staffMember)', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('appeal', 'Appeal'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
