# Generated by Django 5.1.3 on 2025-01-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_rewardspointstracker_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardspointstracker',
            name='transaction_type',
            field=models.CharField(choices=[('merit', 'Merit'), ('assisted', 'Assisted'), ('pending', 'Pending'), ('staffMember', 'Staff Member')], default='merit', help_text='Type of transaction (merit, assisted, staffMember, pending)', max_length=20),
        ),
    ]
