# Generated by Django 5.1.3 on 2025-01-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_alter_rewardspointstracker_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('appeal', 'Appeal'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rewardGranted', 'Reward Granted')], default='active', max_length=20),
        ),
    ]
