# Generated by Django 5.1.3 on 2025-01-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_alter_expectations_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_date'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
    ]
