# Generated by Django 5.1.3 on 2025-01-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityowner',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
