# Generated by Django 5.1.3 on 2025-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_activityowner_interval_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityowner',
            name='reoccurring',
            field=models.BooleanField(default=False, help_text='Indicates if the activity is reoccurring.'),
        ),
        migrations.AddField(
            model_name='activityowner',
            name='reoccurring_End',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityowner',
            name='reoccurring_Start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
